name: Build Apps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SDL2 and X11 Dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libx11-dev \
            libxext-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxrandr-dev \
            libxss-dev \
            libxxf86vm-dev \
            libwayland-dev \
            libwayland-client0 \
            libwayland-cursor0 \
            libwayland-egl1 \
            libxkbcommon-dev \
            wayland-protocols
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-2.28.5.tar.gz
          tar xzf SDL2-2.28.5.tar.gz
          cd SDL2-2.28.5
          ./configure --prefix=/usr/local --enable-static --disable-shared
          make -j$(nproc)
          sudo make install
          
      - name: Setup MinGW and SDL2 (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install mingw --version=8.1.0 -y
          # Download and extract SDL2 development files for MinGW
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-mingw.zip -o SDL2.zip
          7z x SDL2.zip
          # Copy headers and libs to MinGW directories
          mkdir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\include\SDL2
          xcopy /E /I /Y SDL2-2.28.5\x86_64-w64-mingw32\include\SDL2\* C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\include\SDL2\
          copy SDL2-2.28.5\x86_64-w64-mingw32\lib\*.a C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\lib\
          # Also copy SDL2.dll to the build directory
          copy SDL2-2.28.5\x86_64-w64-mingw32\bin\SDL2.dll native\
          
      - name: Build Native App (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cd native
          chmod +x compile.sh
          ./compile.sh
          
      - name: Build Native App (Windows)
        if: matrix.platform == 'windows-latest'
        shell: cmd
        run: |
          cd native
          set PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
          compile.bat
          
      - name: Upload Native Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.platform }}
          path: |
            native/googleballs-desktop*
            native/*.exe
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      
      - name: Install Dependencies (Tauri)
        run: |
          cd tauri
          npm install
          
      - name: Build Tauri App
        run: |
          cd tauri
          npm run tauri build
          
      - name: Upload Tauri Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}
          path: |
            tauri/src-tauri/target/release/bundle/
            
  build-electron:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Setup GitHub token
        if: matrix.platform == 'windows-latest'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GH_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
          
      - name: Install Dependencies (Electron)
        run: |
          cd electron
          npm install
          
      - name: Build Electron App
        run: |
          cd electron
          npm run dist
          
      - name: Upload Electron Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.platform }}
          path: electron/dist/
